graph TD
    subgraph User
        A["Website (React)"]
    end

    subgraph Orchestrating LLM
        LLM["LLM (OpenAI, Claude, etc.)"]
    end
    
    subgraph "AWS"
            B["Route 53"]
            A --> B
            B --> C[API Gateway]
            subgraph "AWS Region 1"
                
                C --> D["Application Load Balancer (ELB)"]
                
                subgraph ECS
                    subgraph "App (ECS Service)"
                        E["Backend Api (FastAPI)"]
                    end 
                    subgraph "MCP (ECS Service)"
                        F["MCP Client (FastAgent)"]
                        F -->|Spawns via uvx| G["MCP Server Process (e.g. Cortex)"]
                    end
                end
                F <--> LLM
                D --> E

                E -->|HTTP /chat| F
                E -->|Calls| I[AuthZ Service]
            end

            I -.->|Validates Session Cookie| E
        end

    subgraph Snowflake
        H["Cortex APIs"]
    end

    G -->|Tool API Calls| H