# ecs_definitions/service.yaml
Resources:
  BackendAppService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ClusterName
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref BackendTaskDef
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: [subnet-xxxxxx]
          SecurityGroups: [sg-xxxxxx]
          AssignPublicIp: ENABLED
      ServiceName: backend-app

  MCPClientService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ClusterName
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref ClientTaskDef
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: [subnet-xxxxxx]
          SecurityGroups: [sg-xxxxxx]
          AssignPublicIp: ENABLED
      ServiceName: mcp-client